version: "3.5"
services:
        mysql:
                image: ushakiran20/mysql-updated
                container_name: mysqlhost2
                ports:
                        - 3306:3306
                secrets:
                        - DB_USERNAME
                        - DB_PASSWORD
                volumes:
                        - mysql-data:/var/lib/mysql/
                environment:
                        - MYSQL_ROOT_PASSWORD=/run/secrets/ROOT_PASSWORD
        apache:
                image: ushakiran20/apache2-updated
                container_name: apachehost
                depends_on:
                        - mysql
                ports:
                        - 8085:80
                secrets:
                        - DB_USERNAME
                        - DB_PASSWORD
                volumes:
                        - web-data:/var/lib/apache2/
secrets:
        DB_USERNAME:
                external: true
        DB_PASSWORD:
                external: true
volumes:
        mysql-data:
        web-data: